---
# Tasks for compute-node

# BIOS updates for Dell C6320
#
- name: Copy new BIOS update to /tmp
  tags: bios
  copy: src=files/Dell/{{ bios_update_name }} mode=0755 dest=/tmp
  register: update_needed
  when: (ansible_bios_version != "2.2.5")
  notify: Remove temporary bios update file

- name: Install BIOS update
  tags: bios
  shell: /tmp/{{ bios_update_name }} -q
  register: bios_updated
  when: update_needed.changed
  failed_when: > 
    bios_updated.rc != 2 and ("same as the currently installed" not in bios_updated.stdout)
  changed_when: bios_updated.rc == 2 
  notify: Request Reboot
