---

# Let's find out model
- name: Registering HW model of Dell
  shell: /usr/sbin/dmidecode -s system-product-name| cut -d " " -f2
  register: Dell_model
- debug: var=Dell_model

# BIOS updates for Dell HW

- name: Copy new BIOS update to /tmp
  tags: bios
  copy: src=Dell/{{ bios_newest_name }} mode=0755 dest=/tmp
  register: update_needed
  when: ( "{{ ansible_bios_version }}" != "{{ bios_newest_version }}" )
  notify: Remove temporary bios update file

- name: Install BIOS update
  tags: bios
  shell: /tmp/{{ bios_newest_name }} -q
  register: bios_updated
  when: update_needed.changed
  failed_when: > 
    bios_updated.rc != 2 and ("same as the currently installed" not in bios_updated.stdout)
  changed_when: bios_updated.rc == 2 
# These are mostly servers, so we just can't request shutdown from slurm
  notify: Request Reboot
  

# IB firmware update for dell Mellanox IB cards
# PSID: DEL1100001019
#
- name: Check current IB fw version
  tags: IB
  script: files/check_ib_fw.sh
  register: IB_version
  when: infiniband_available

- name: Copy new FW update to /tmp
  tags: IB
  copy: src=Dell/{{ ib_firmware_newest_name }} mode=0644 dest=/tmp
  register: update_needed
  when: ( "{{ IB_version.stdout }}" != "{{ ib_firmware_newest_version }}" )
  notify: Remove temporary fw update file

- name: Install FW update
  tags: IB
  shell: mstflint -q -s -nofs -y -d `lspci |grep -i mellanox |cut -d " " -f1` -i /tmp/{{ ib_firmware_newest_name }} burn
  register: fw_updated
  when: update_needed.changed
  failed_when: > 
    fw_updated.rc != 0 and ("The new FW version is the same as the current FW version on flash." not in fw_updated.stdout)
  changed_when: fw_updated.rc == 0 
  notify: Request Reboot

- name: Check current iDRAC version
  tags: idrac
  script: files/check_idrac_version.sh
  register: idrac_version

- name: Copy new idrac FW to /tmp
  tags: idrac
  copy: src=Dell/{{ idrac_newest_name }} mode=0755 dest=/tmp
  register: idrac_update_needed
  when: idrac_version.stdout | version_compare ( "{{ idrac_newest_version }}", "<" )
  notify: Remove temporary idrac update file

- name: Install iDRAC FW update
  tags: idrac
  shell: /tmp/{{ idrac_newest_name }} -q
  register: idrac_updated
  when: idrac_update_needed.changed
  changed_when: idrac_updated.rc == 0 

