---

# BIOS updates for HP HW

- name: ipmitools is installed
  tags: ilo
  yum: name=freeipmi state=installed

- name: Check current iLO version
  tags: ilo,debug
  script: files/check_idrac_version.sh
  register: ilo_version

- debug: 
    msg: 
      - "iLO Firmware-version: {{ ilo_version.stdout |trim }}"
      - "iLO newest Firmware-version: {{ ilo_newest_version[ansible_product_name] }}"
  tags: ilo,debug

- name: Copy new iLO FW to /tmp
  tags: ilo
  copy: src=HP/{{ ilo_newest_name[ansible_product_name] }} mode=0755 dest=/tmp
  register: ilo_update_needed
  when: ilo_version.stdout is version_compare ( 'ilo_newest_version[ansible_product_name]' , '<' )
  notify: Remove temporary ilo update file

- name: Install iLO FW update
  tags: ilo
  shell: /tmp/{{ ilo_newest_name[ansible_product_name] }} -s
  register: ilo_updated
  when: ilo_update_needed.changed
  failed_when: > 
    ilo_updated.rc != 0 and ilo_updated.rc != 2
  changed_when: ilo_updated.rc == 0 
  notify: Reset iLO configuration

- name: Request iLO configuration reset
  tags: ilo-reset
  debug: msg="Requesting iLO configuration reset"
  changed_when: True
  when: ilo_updated.rc is defined and ilo_updated.rc == 0
  notify: Reset iLO configuration

- debug: 
    msg:
     - "Ansible bios-version {{ ansible_bios_date }}"
     - "Newest bios-version {{ bios_newest_version[ansible_product_name] }}"
  tags: bios,debug

- name: Extract BIOS update package
  tags: bios
  unarchive: 
    src: HP/{{ bios_newest_name[ansible_product_name] }}
    dest: /tmp
  when: ansible_bios_date != bios_newest_version[ansible_product_name] 
  notify: Remove temporary bios update file

- name: Install BIOS update
  tags: bios
  shell: /tmp/usr/lib/i386-linux-gnu/firmware-system-*/hpsetup -s
  register: bios_updated
  when: ( ansible_bios_date != bios_newest_version[ansible_product_name] )
  failed_when: > 
    bios_updated.rc != 1 and bios_updated.rc != 2
  changed_when: bios_updated.rc == 1 
# These are mostly servers, so we just can't request shutdown from slurm
  notify: Request Reboot

# IB firmware update moved to separate infiniband.yml
#

