- name: Remove temporary bios update file
  file: name=/tmp/usr state=absent

- name: Remove temporary fw update file
  file: name=/tmp/{{ ib_newest_name }} state=absent

- name: Remove temporary idrac update file
  file: name=/tmp/{{ idrac_newest_name }} state=absent

- name: Remove temporary ilo update file
  file: name=/tmp/{{ ilo_newest_name }} state=absent

- name: Remove temporary perc update file
  file: name=/tmp/{{ perc_newest_name[perc_version] }} state=absent

- name: Remove perccli rpm
  file: name=/tmp/{{ perccli_newest_name }} state=absent

- name: Request Reboot
  command: /usr/bin/scontrol update nodename="{{ ansible_hostname }}" state=drain reason=reboot
  when: (inventory_hostname in groups.compute)

- name: Reset iLO configuration
  tags: ilo-reset
  shell: /home/mmoa/firmware-config/configure-iLO.sh

